In [1]:
from __future__ import print_function
import argparse
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.autograd import Variable

In [2]:
batch_size = 64

In [4]:
train_dataset = datasets.MNIST(root='./data/',
                              train=True,
                              transform = transforms.ToTensor(),
                              download=True)

test_dataset = datasets.MNIST(root='./data/',
                             train=False,
                             transform = transforms.ToTensor())

Processing...
Done!


In [7]:
train_loader = torch.utils.data.DataLoader(dataset = train_dataset,
                                          batch_size = batch_size,
                                          shuffle = True)

test_loader = torch.utils.data.DataLoader(dataset = test_dataset,
                                         batch_size = batch_size,
                                         shuffle = False)

In [8]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, kernel_size = 5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size = 5)
        self.mp = nn.MaxPool2d(2)
        self.fc = nn.Linear(320, 10)
        
    def forward(self, x):
        in_size = x.size(0)
        x = F.relu(self.mp(self.conv1(x)))
        x = F.relu(self.mp(self.conv2(x)))
        x = x.view(in_size, -1)
        x = self.fc(x)
        return F.log_softmax(x)
    
model = Net()

In [9]:
optimizer = optim.SGD(model.parameters(), lr = 0.01, momentum = 0.5)

In [19]:
def train(epoch):
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = Variable(data), Variable(target)
        optimizer.zero_grad()
        output = model(data)
        loss = F.nll_loss(output, target)
        loss.backward()
        optimizer.step()
        if batch_idx % 10 == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
            epoch, batch_idx * len(data), len(train_loader.dataset),
            100. * batch_idx / len(train_loader), loss.data[0]))

In [20]:
def test():
    model.eval()
    test_loss = 0
    correct = 0
    for data, target in test_loader:
        data, target = Variable(data, volatile=True), Variable(target)
        output = model(data)
        # sum up batch loss
        test_loss += F.nll_loss(output, target, size_average=False).data[0]
        # get the index of the max log-probability
        pred = output.data.max(1, keepdim=True)[1]
        correct += pred.eq(target.data.view_as(pred)).cpu().sum()
        
    test_loss /= len(test_loader.dataset)
    print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
        test_loss, correct, len(test_loader.dataset),
        100. * correct / len(test_loader.dataset)))

In [21]:
for epoch in range(1, 10):
    train(epoch)
    test()

D:\Anaconda3\envs\pytorch\lib\site-packages\ipykernel_launcher.py:15: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  from ipykernel import kernelapp as app
D:\Anaconda3\envs\pytorch\lib\site-packages\ipykernel_launcher.py:13: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  del sys.path[0]


Train Epoch: 1 [0/60000 (0%)]	Loss: 0.118703
Train Epoch: 1 [640/60000 (1%)]	Loss: 0.174191
Train Epoch: 1 [1280/60000 (2%)]	Loss: 0.076240
Train Epoch: 1 [1920/60000 (3%)]	Loss: 0.151528
Train Epoch: 1 [2560/60000 (4%)]	Loss: 0.002645
Train Epoch: 1 [3200/60000 (5%)]	Loss: 0.047591
Train Epoch: 1 [3840/60000 (6%)]	Loss: 0.067243
Train Epoch: 1 [4480/60000 (7%)]	Loss: 0.033599
Train Epoch: 1 [5120/60000 (9%)]	Loss: 0.053056
Train Epoch: 1 [5760/60000 (10%)]	Loss: 0.049680
Train Epoch: 1 [6400/60000 (11%)]	Loss: 0.024984
Train Epoch: 1 [7040/60000 (12%)]	Loss: 0.037368
Train Epoch: 1 [7680/60000 (13%)]	Loss: 0.102333
Train Epoch: 1 [8320/60000 (14%)]	Loss: 0.022356
Train Epoch: 1 [8960/60000 (15%)]	Loss: 0.063179
Train Epoch: 1 [9600/60000 (16%)]	Loss: 0.085596
Train Epoch: 1 [10240/60000 (17%)]	Loss: 0.070041
Train Epoch: 1 [10880/60000 (18%)]	Loss: 0.024907
Train Epoch: 1 [11520/60000 (19%)]	Loss: 0.044657
Train Epoch: 1 [12160/60000 (20%)]	Loss: 0.054738
Train Epoch: 1 [12800/60000 (

D:\Anaconda3\envs\pytorch\lib\site-packages\ipykernel_launcher.py:6: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  
D:\Anaconda3\envs\pytorch\lib\site-packages\ipykernel_launcher.py:9: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  if __name__ == '__main__':



Test set: Average loss: 0.0407, Accuracy: 9876/10000 (98%)

Train Epoch: 2 [0/60000 (0%)]	Loss: 0.030730
Train Epoch: 2 [640/60000 (1%)]	Loss: 0.081251
Train Epoch: 2 [1280/60000 (2%)]	Loss: 0.059101
Train Epoch: 2 [1920/60000 (3%)]	Loss: 0.037823
Train Epoch: 2 [2560/60000 (4%)]	Loss: 0.098059
Train Epoch: 2 [3200/60000 (5%)]	Loss: 0.029917
Train Epoch: 2 [3840/60000 (6%)]	Loss: 0.063397
Train Epoch: 2 [4480/60000 (7%)]	Loss: 0.292198
Train Epoch: 2 [5120/60000 (9%)]	Loss: 0.321505
Train Epoch: 2 [5760/60000 (10%)]	Loss: 0.008019
Train Epoch: 2 [6400/60000 (11%)]	Loss: 0.021584
Train Epoch: 2 [7040/60000 (12%)]	Loss: 0.034461
Train Epoch: 2 [7680/60000 (13%)]	Loss: 0.008756
Train Epoch: 2 [8320/60000 (14%)]	Loss: 0.014156
Train Epoch: 2 [8960/60000 (15%)]	Loss: 0.072415
Train Epoch: 2 [9600/60000 (16%)]	Loss: 0.097669
Train Epoch: 2 [10240/60000 (17%)]	Loss: 0.012686
Train Epoch: 2 [10880/60000 (18%)]	Loss: 0.043345
Train Epoch: 2 [11520/60000 (19%)]	Loss: 0.006192
Train Epoch: 2 [12

Train Epoch: 3 [44800/60000 (75%)]	Loss: 0.063532
Train Epoch: 3 [45440/60000 (76%)]	Loss: 0.011714
Train Epoch: 3 [46080/60000 (77%)]	Loss: 0.022773
Train Epoch: 3 [46720/60000 (78%)]	Loss: 0.005875
Train Epoch: 3 [47360/60000 (79%)]	Loss: 0.024247
Train Epoch: 3 [48000/60000 (80%)]	Loss: 0.005309
Train Epoch: 3 [48640/60000 (81%)]	Loss: 0.003097
Train Epoch: 3 [49280/60000 (82%)]	Loss: 0.002743
Train Epoch: 3 [49920/60000 (83%)]	Loss: 0.054374
Train Epoch: 3 [50560/60000 (84%)]	Loss: 0.005288
Train Epoch: 3 [51200/60000 (85%)]	Loss: 0.009834
Train Epoch: 3 [51840/60000 (86%)]	Loss: 0.017833
Train Epoch: 3 [52480/60000 (87%)]	Loss: 0.006051
Train Epoch: 3 [53120/60000 (88%)]	Loss: 0.018903
Train Epoch: 3 [53760/60000 (90%)]	Loss: 0.005638
Train Epoch: 3 [54400/60000 (91%)]	Loss: 0.019823
Train Epoch: 3 [55040/60000 (92%)]	Loss: 0.007695
Train Epoch: 3 [55680/60000 (93%)]	Loss: 0.006661
Train Epoch: 3 [56320/60000 (94%)]	Loss: 0.031752
Train Epoch: 3 [56960/60000 (95%)]	Loss: 0.004438


Train Epoch: 5 [29440/60000 (49%)]	Loss: 0.036491
Train Epoch: 5 [30080/60000 (50%)]	Loss: 0.027176
Train Epoch: 5 [30720/60000 (51%)]	Loss: 0.027853
Train Epoch: 5 [31360/60000 (52%)]	Loss: 0.026909
Train Epoch: 5 [32000/60000 (53%)]	Loss: 0.027616
Train Epoch: 5 [32640/60000 (54%)]	Loss: 0.040102
Train Epoch: 5 [33280/60000 (55%)]	Loss: 0.004501
Train Epoch: 5 [33920/60000 (57%)]	Loss: 0.035485
Train Epoch: 5 [34560/60000 (58%)]	Loss: 0.040947
Train Epoch: 5 [35200/60000 (59%)]	Loss: 0.017051
Train Epoch: 5 [35840/60000 (60%)]	Loss: 0.009340
Train Epoch: 5 [36480/60000 (61%)]	Loss: 0.023158
Train Epoch: 5 [37120/60000 (62%)]	Loss: 0.037911
Train Epoch: 5 [37760/60000 (63%)]	Loss: 0.047909
Train Epoch: 5 [38400/60000 (64%)]	Loss: 0.076627
Train Epoch: 5 [39040/60000 (65%)]	Loss: 0.037609
Train Epoch: 5 [39680/60000 (66%)]	Loss: 0.029630
Train Epoch: 5 [40320/60000 (67%)]	Loss: 0.048328
Train Epoch: 5 [40960/60000 (68%)]	Loss: 0.089464
Train Epoch: 5 [41600/60000 (69%)]	Loss: 0.014009


Train Epoch: 7 [13440/60000 (22%)]	Loss: 0.028747
Train Epoch: 7 [14080/60000 (23%)]	Loss: 0.011305
Train Epoch: 7 [14720/60000 (25%)]	Loss: 0.031986
Train Epoch: 7 [15360/60000 (26%)]	Loss: 0.014296
Train Epoch: 7 [16000/60000 (27%)]	Loss: 0.014672
Train Epoch: 7 [16640/60000 (28%)]	Loss: 0.022620
Train Epoch: 7 [17280/60000 (29%)]	Loss: 0.011899
Train Epoch: 7 [17920/60000 (30%)]	Loss: 0.003275
Train Epoch: 7 [18560/60000 (31%)]	Loss: 0.011557
Train Epoch: 7 [19200/60000 (32%)]	Loss: 0.055638
Train Epoch: 7 [19840/60000 (33%)]	Loss: 0.029214
Train Epoch: 7 [20480/60000 (34%)]	Loss: 0.019850
Train Epoch: 7 [21120/60000 (35%)]	Loss: 0.022813
Train Epoch: 7 [21760/60000 (36%)]	Loss: 0.101634
Train Epoch: 7 [22400/60000 (37%)]	Loss: 0.038395
Train Epoch: 7 [23040/60000 (38%)]	Loss: 0.005064
Train Epoch: 7 [23680/60000 (39%)]	Loss: 0.030754
Train Epoch: 7 [24320/60000 (41%)]	Loss: 0.061013
Train Epoch: 7 [24960/60000 (42%)]	Loss: 0.044220
Train Epoch: 7 [25600/60000 (43%)]	Loss: 0.061296


Train Epoch: 8 [58240/60000 (97%)]	Loss: 0.171757
Train Epoch: 8 [58880/60000 (98%)]	Loss: 0.070024
Train Epoch: 8 [59520/60000 (99%)]	Loss: 0.047231

Test set: Average loss: 0.0370, Accuracy: 9881/10000 (98%)

Train Epoch: 9 [0/60000 (0%)]	Loss: 0.022485
Train Epoch: 9 [640/60000 (1%)]	Loss: 0.013186
Train Epoch: 9 [1280/60000 (2%)]	Loss: 0.005059
Train Epoch: 9 [1920/60000 (3%)]	Loss: 0.021437
Train Epoch: 9 [2560/60000 (4%)]	Loss: 0.052724
Train Epoch: 9 [3200/60000 (5%)]	Loss: 0.110801
Train Epoch: 9 [3840/60000 (6%)]	Loss: 0.004671
Train Epoch: 9 [4480/60000 (7%)]	Loss: 0.065487
Train Epoch: 9 [5120/60000 (9%)]	Loss: 0.104455
Train Epoch: 9 [5760/60000 (10%)]	Loss: 0.014537
Train Epoch: 9 [6400/60000 (11%)]	Loss: 0.020132
Train Epoch: 9 [7040/60000 (12%)]	Loss: 0.024706
Train Epoch: 9 [7680/60000 (13%)]	Loss: 0.089766
Train Epoch: 9 [8320/60000 (14%)]	Loss: 0.017748
Train Epoch: 9 [8960/60000 (15%)]	Loss: 0.057449
Train Epoch: 9 [9600/60000 (16%)]	Loss: 0.029866
Train Epoch: 9 [10

In [22]:
for batch_idx, (data, target) in enumerate(train_loader):
        data, target = Variable(data), Variable(target)
        print(data)
        print(target)

tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.000

tensor([ 1,  1,  2,  1,  3,  9,  0,  5,  2,  5,  2,  7,  1,  2,
         1,  2,  1,  0,  2,  2,  3,  9,  5,  6,  7,  1,  1,  7,
         8,  1,  4,  8,  4,  9,  4,  5,  6,  0,  5,  7,  0,  4,
         1,  9,  6,  8,  1,  1,  5,  9,  7,  1,  4,  2,  7,  7,
         3,  3,  5,  9,  9,  2,  2,  4])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 7,  8,  7,  5,  8,  8,  1,  8,  0,  2,  3,  2,  0,  9,
         6,  8,  3,  0,  0,  1,  0,  0,  9,  6,  1,  6,  6,  3,
         7,  3,  6,  2,  1,  9,  7,  4,  1,  9,  1,  1,  6,  8,
         6,  4,  7,  8,  7,  4,  3,  3,  2,  7,  6,  4,  8,  4,
         7,  5,  3,  5,  3,  6,  6,  1])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 9,  3,  3,  6,  5,  5,  0,  3,  5,  1,  3,  9,  0,  9,
         4,  8,  4,  1,  3,  6,  6,  4,  8,  4,  6,  4,  7,  1,
         5,  8,  8,  6,  0,  8,  6,  2,  8,  9,  1,  6,  0,  0,
         6,  2,  4,  4,  6,  1,  8,  8,  6,  2,  2,  7,  6,  7,
         5,  9,  1,  3,  5,  9,  6,  9])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 2,  6,  8,  8,  7,  3,  4,  4,  4,  6,  9,  1,  4,  9,
         2,  4,  8,  0,  3,  9,  9,  9,  4,  9,  8,  6,  9,  9,
         2,  5,  5,  3,  7,  8,  1,  5,  5,  7,  9,  9,  5,  7,
         8,  5,  6,  8,  6,  6,  7,  2,  1,  7,  2,  5,  2,  0,
         1,  7,  1,  8,  3,  6,  4,  7])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 0,  4,  5,  6,  7,  9,  0,  9,  6,  4,  4,  8,  6,  9,
         5,  3,  9,  3,  0,  8,  9,  7,  4,  9,  0,  2,  9,  5,
         0,  7,  3,  4,  8,  2,  1,  0,  5,  1,  3,  0,  3,  8,
         1,  5,  1,  3,  1,  2,  1,  1,  4,  3,  2,  0,  9,  8,
         9,  1,  0,  7,  9,  8,  2,  9])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 9,  9,  0,  2,  4,  3,  6,  7,  7,  7,  8,  8,  5,  6,
         3,  0,  9,  6,  3,  8,  0,  0,  9,  6,  9,  0,  9,  0,
         0,  9,  0,  7,  5,  0,  2,  5,  1,  3,  3,  8,  3,  1,
         3,  5,  4,  9,  6,  5,  8,  9,  5,  9,  1,  8,  6,  7,
         3,  9,  6,  2,  2,  6,  1,  5])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 9,  7,  4,  2,  1,  2,  9,  3,  0,  0,  3,  6,  3,  3,
         0,  3,  5,  2,  7,  3,  4,  0,  7,  6,  0,  8,  1,  2,
         3,  8,  9,  1,  7,  1,  5,  3,  7,  9,  5,  1,  1,  9,
         4,  5,  7,  1,  1,  2,  1,  8,  2,  6,  1,  9,  6,  6,
         6,  2,  6,  0,  3,  7,  0,  7])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 3,  1,  8,  1,  5,  3,  9,  7,  9,  1,  6,  7,  5,  2,
         2,  0,  7,  5,  4,  2,  7,  3,  3,  5,  5,  0,  3,  3,
         9,  0,  7,  1,  2,  1,  4,  2,  1,  6,  8,  0,  4,  6,
         3,  2,  2,  9,  7,  1,  1,  8,  8,  0,  3,  2,  8,  2,
         3,  4,  4,  8,  3,  8,  8,  4])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 7,  2,  7,  6,  5,  1,  4,  4,  2,  9,  2,  5,  1,  4,
         7,  5,  8,  8,  3,  3,  6,  0,  7,  9,  2,  8,  6,  3,
         3,  8,  6,  7,  1,  9,  3,  2,  4,  4,  9,  0,  1,  4,
         6,  3,  9,  2,  0,  7,  2,  1,  2,  4,  1,  8,  5,  9,
         6,  1,  9,  4,  3,  6,  3,  3])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 6,  2,  6,  9,  0,  9,  2,  4,  1,  9,  0,  3,  0,  3,
         8,  9,  0,  8,  5,  9,  6,  4,  2,  9,  9,  4,  8,  1,
         0,  1,  6,  9,  1,  7,  2,  9,  4,  9,  7,  8,  0,  8,
         2,  6,  8,  1,  7,  7,  8,  8,  4,  8,  8,  2,  0,  7,
         1,  7,  8,  7,  6,  2,  7,  9])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 4,  1,  8,  5,  4,  8,  7,  5,  6,  8,  9,  1,  9,  8,
         0,  2,  9,  3,  1,  4,  0,  8,  5,  7,  1,  6,  1,  5,
         9,  3,  1,  9,  9,  4,  4,  0,  7,  1,  1,  1,  0,  1,
         9,  0,  0,  0,  4,  1,  6,  8,  6,  3,  5,  8,  3,  7,
         2,  2,  4,  7,  4,  3,  7,  8])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 7,  6,  8,  3,  8,  4,  5,  3,  7,  3,  8,  6,  3,  5,
         0,  2,  3,  4,  0,  1,  9,  7,  6,  6,  0,  1,  0,  3,
         8,  6,  2,  3,  9,  3,  1,  4,  6,  1,  0,  1,  4,  3,
         2,  6,  6,  4,  4,  4,  7,  1,  0,  5,  1,  6,  2,  9,
         5,  8,  9,  6,  8,  9,  0,  1])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.000

tensor([ 3,  8,  0,  0,  6,  9,  0,  6,  7,  3,  2,  4,  0,  4,
         6,  8,  5,  8,  7,  1,  5,  6,  5,  6,  3,  1,  1,  1,
         6,  0,  9,  0,  5,  0,  1,  1,  3,  9,  1,  5,  7,  3,
         2,  3,  1,  7,  6,  9,  0,  7,  0,  8,  0,  3,  0,  4,
         3,  4,  1,  7,  4,  1,  5,  6])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 5,  6,  4,  3,  3,  2,  7,  9,  3,  0,  3,  9,  5,  1,
         6,  1,  0,  4,  2,  1,  7,  2,  3,  8,  4,  1,  4,  7,
         0,  6,  8,  9,  4,  1,  0,  4,  1,  4,  9,  6,  4,  2,
         7,  9,  8,  4,  1,  9,  6,  1,  8,  1,  5,  8,  0,  1,
         8,  1,  5,  8,  3,  7,  0,  5])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

         3,  1,  0,  8,  3,  6,  8,  4])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0

tensor([ 6,  3,  7,  9,  7,  6,  2,  7,  3,  1,  7,  8,  8,  6,
         3,  5,  2,  1,  4,  2,  4,  5,  4,  6,  0,  0,  0,  9,
         5,  1,  7,  4,  0,  1,  2,  9,  8,  1,  9,  2,  2,  4,
         8,  7,  7,  0,  8,  0,  6,  1,  8,  0,  2,  5,  7,  6,
         4,  7,  3,  1,  1,  4,  3,  6])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 0,  8,  1,  3,  7,  9,  7,  0,  0,  9,  4,  4,  2,  7,
         1,  8,  2,  9,  5,  7,  6,  6,  8,  1,  0,  8,  4,  2,
         8,  2,  0,  2,  8,  6,  5,  2,  3,  5,  1,  0,  6,  6,
         5,  4,  4,  9,  5,  9,  6,  5,  0,  9,  6,  3,  9,  1,
         9,  5,  3,  6,  3,  7,  8,  0])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 4,  8,  5,  0,  6,  3,  2,  4,  7,  1,  2,  7,  2,  9,
         3,  2,  6,  6,  0,  5,  8,  2,  5,  0,  8,  4,  8,  3,
         1,  5,  9,  8,  7,  1,  5,  5,  1,  1,  1,  8,  2,  9,
         2,  7,  1,  4,  1,  9,  8,  7,  0,  1,  5,  6,  1,  4,
         8,  5,  4,  4,  1,  8,  6,  1])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 6,  9,  1,  0,  5,  3,  8,  8,  1,  9,  1,  4,  9,  6,
         3,  8,  2,  3,  1,  9,  8,  3,  9,  7,  9,  5,  8,  6,
         3,  4,  1,  5,  4,  3,  6,  1,  9,  2,  9,  0,  6,  2,
         7,  2,  1,  9,  8,  5,  3,  8,  3,  2,  4,  9,  9,  7,
         2,  6,  3,  9,  3,  3,  7,  7])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 5,  7,  5,  0,  0,  0,  5,  4,  0,  7,  9,  7,  9,  8,
         6,  8,  2,  1,  7,  4,  1,  6,  3,  0,  2,  1,  8,  4,
         9,  4,  2,  9,  6,  1,  6,  2,  0,  7,  5,  9,  5,  3,
         3,  2,  1,  2,  8,  2,  3,  5,  9,  7,  7,  7,  5,  8,
         0,  1,  4,  6,  7,  3,  7,  2])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 0,  2,  4,  9,  9,  2,  2,  1,  7,  5,  2,  1,  3,  4,
         8,  9,  7,  5,  1,  5,  6,  1,  4,  6,  9,  2,  4,  6,
         6,  9,  5,  8,  8,  9,  4,  3,  7,  2,  8,  1,  4,  1,
         2,  7,  6,  3,  2,  3,  1,  4,  8,  9,  3,  0,  7,  3,
         3,  8,  5,  6,  0,  4,  3,  4])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 4,  6,  8,  6,  7,  9,  1,  5,  6,  9,  1,  5,  8,  2,
         3,  1,  9,  9,  7,  4,  0,  9,  8,  3,  4,  0,  4,  7,
         2,  1,  0,  7,  6,  1,  2,  4,  5,  1,  0,  4,  1,  3,
         6,  6,  1,  0,  7,  7,  1,  3,  0,  8,  6,  5,  7,  7,
         6,  2,  4,  2,  4,  6,  2,  0])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 9,  4,  9,  9,  1,  1,  0,  5,  2,  7,  5,  7,  0,  9,
         2,  3,  2,  5,  8,  6,  7,  7,  4,  0,  9,  3,  0,  6,
         5,  7,  7,  3,  5,  4,  0,  3,  9,  8,  4,  2,  1,  0,
         4,  6,  1,  3,  1,  7,  4,  7,  1,  2,  7,  9,  4,  6,
         5,  3,  5,  8,  3,  6,  3,  3])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 4,  2,  8,  8,  7,  2,  6,  0,  6,  2,  7,  2,  5,  9,
         0,  0,  5,  4,  2,  1,  2,  6,  8,  3,  5,  0,  0,  9,
         5,  4,  3,  5,  6,  5,  6,  7,  3,  1,  3,  6,  6,  7,
         4,  0,  4,  9,  5,  2,  3,  3,  6,  5,  3,  4,  1,  0,
         3,  9,  6,  7,  6,  2,  0,  5])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 5,  3,  2,  8,  3,  1,  0,  8,  5,  0,  3,  0,  6,  3,
         3,  9,  5,  9,  7,  1,  6,  4,  7,  0,  6,  3,  1,  3,
         9,  0,  4,  6,  1,  0,  8,  9,  2,  8,  9,  3,  0,  3,
         2,  1,  0,  4,  3,  1,  2,  3,  9,  3,  3,  4,  9,  9,
         8,  8,  2,  4,  0,  6,  1,  0])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 6,  1,  7,  7,  8,  7,  0,  4,  5,  3,  2,  6,  7,  0,
         3,  5,  3,  9,  0,  1,  9,  2,  2,  2,  2,  8,  3,  3,
         0,  5,  8,  5,  1,  5,  0,  7,  1,  2,  7,  6,  6,  8,
         9,  0,  3,  6,  3,  3,  5,  2,  3,  3,  2,  1,  3,  8,
         3,  5,  2,  7,  7,  3,  4,  5])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 2,  4,  6,  9,  6,  5,  2,  6,  0,  0,  4,  3,  5,  9,
         8,  5,  0,  6,  3,  3,  4,  2,  9,  7,  8,  7,  7,  8,
         7,  7,  0,  0,  0,  3,  5,  0,  6,  3,  1,  9,  5,  7,
         7,  8,  0,  1,  0,  9,  6,  6,  7,  8,  4,  4,  1,  1,
         2,  7,  5,  5,  5,  6,  7,  3])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 9,  6,  9,  9,  1,  3,  7,  2,  3,  5,  0,  2,  0,  6,
         3,  5,  0,  3,  4,  2,  3,  7,  8,  6,  4,  2,  5,  8,
         6,  0,  1,  2,  1,  6,  6,  1,  6,  3,  8,  7,  4,  6,
         3,  7,  0,  7,  3,  1,  9,  9,  0,  9,  3,  8,  7,  9,
         5,  8,  7,  6,  3,  1,  5,  5])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 3,  4,  2,  3,  5,  6,  2,  2,  3,  1,  9,  5,  5,  7,
         6,  7,  1,  0,  0,  0,  4,  0,  3,  2,  0,  3,  4,  0,
         5,  0,  1,  6,  5,  5,  2,  9,  8,  6,  8,  4,  0,  7,
         7,  1,  2,  6,  0,  2,  0,  2,  4,  2,  0,  3,  6,  7,
         3,  4,  1,  7,  5,  0,  8,  5])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 3,  6,  0,  4,  0,  4,  3,  8,  3,  0,  3,  8,  8,  4,
         7,  9,  2,  4,  0,  2,  2,  7,  0,  2,  0,  1,  8,  0,
         5,  4,  1,  7,  7,  4,  9,  9,  7,  4,  8,  1,  8,  5,
         2,  6,  6,  3,  6,  7,  0,  8,  1,  8,  0,  4,  1,  7,
         3,  7,  0,  5,  9,  3,  6,  4])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 2,  2,  3,  0,  7,  2,  4,  3,  6,  4,  6,  7,  1,  2,
         8,  7,  2,  7,  6,  1,  2,  4,  7,  3,  3,  0,  1,  6,
         3,  3,  8,  3,  2,  0,  0,  5,  3,  8,  8,  4,  4,  2,
         5,  6,  0,  0,  5,  2,  2,  9,  5,  1,  0,  2,  1,  2,
         8,  8,  8,  2,  9,  5,  3,  2])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 1,  6,  9,  4,  1,  0,  3,  6,  6,  9,  6,  0,  3,  5,
         7,  9,  3,  4,  2,  1,  9,  5,  4,  7,  7,  5,  0,  0,
         0,  7,  5,  4,  1,  8,  2,  4,  8,  9,  7,  6,  9,  3,
         6,  1,  4,  4,  9,  1,  0,  0,  9,  5,  7,  9,  3,  0,
         8,  7,  4,  3,  4,  6,  8,  9])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 2,  7,  7,  1,  4,  4,  4,  5,  3,  6,  1,  1,  9,  7,
         8,  2,  6,  3,  4,  6,  3,  4,  1,  0,  9,  8,  8,  5,
         4,  6,  7,  1,  2,  9,  4,  3,  3,  8,  1,  2,  6,  2,
         8,  6,  9,  0,  1,  9,  8,  4,  0,  2,  1,  2,  3,  1,
         9,  7,  4,  8,  6,  7,  6,  0])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 3,  3,  8,  0,  8,  1,  9,  0,  6,  3,  2,  6,  7,  5,
         9,  4,  4,  8,  7,  8,  7,  2,  1,  7,  3,  1,  2,  0,
         5,  9,  1,  1,  7,  4,  3,  7,  6,  9,  7,  6,  7,  3,
         8,  5,  7,  0,  9,  9,  7,  8,  0,  9,  6,  1,  5,  7,
         9,  0,  7,  8,  1,  5,  3,  6])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([ 0,  7,  1,  0,  0,  8,  1,  0,  1,  0,  4,  3,  1,  5,
         8,  5,  9,  3,  3,  9,  2,  0,  5,  8,  4,  9,  2,  7,
         0,  0,  4,  3,  6,  6,  5,  2,  5,  6,  6,  7,  6,  2,
         9,  3,  4,  7,  2,  8,  1,  4,  6,  0,  8,  0,  6,  4,
         3,  9,  8,  3,  1,  4,  3,  5])
tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  

tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.000

KeyboardInterrupt: 

In [23]:
ttt = [[1,2], [3,4], [5,6], [7,8]]
for a,b in ttt:
    print(a,b)

1 2
3 4
5 6
7 8
